### ISSUE TITLE
Reproducability in any dataset

### ISSUE THREAD

**Issue by theblackcat102** [ace12358/WordSegmentation#2]
Hi Kitagawa, 

I am interested in reproducing your results, however it seems none of your datasets are available in public and I am not in Japan, hence is there any datasets you can refer to which I could use to reproduce your results?

**Comment by ace12358** [comment]
@theblackcat102 
Thank you for your comment. Our paper used two dataset:
- BCCWJ
- KC

BCCWJ  is not available in public but KC is available. you can get the data to access this link: https://nlp.ist.i.kyoto-u.ac.jp/?%E4%BA%AC%E9%83%BD%E5%A4%A7%E5%AD%A6%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%B3%E3%83%BC%E3%83%91%E3%82%B9

About how to split the data, you should read the previous work.
> we adopted the same train and test split of KC used in previous studies (Kudo et al.,2004; Uchimoto et al., 2001).

**Comment by theblackcat102** [comment]
Thanks for the reply! Searching these datasets is really hard for japanese illiterate like myself. I will take a look into the resources you pointed me for~
